# Generated by Django 5.1.4 on 2025-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('booked', 'Đã có thú cưng')], default='available', max_length=20)),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('expected_check_out_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
