# Generated by Django 4.1.7 on 2025-02-20 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('booked', 'Đã có thú cưng')], default='available', max_length=20)),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('expected_check_out_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('check_in_date', models.DateField()),
                ('expected_check_out_date', models.DateField()),
                ('status', models.CharField(default='booked', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.room')),
            ],
        ),
    ]
