# Generated by Django 5.1.5 on 2025-02-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact_info', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
            ],
        ),
    ]
