# Generated by Django 4.1.7 on 2025-02-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
