# Generated by Django 5.1.6 on 2025-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_booking', models.CharField(max_length=20, unique=True, verbose_name='Mã Booking')),
                ('ten_khach_hang', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('ten_thu_cung', models.CharField(max_length=255, verbose_name='Tên thú cưng')),
                ('check_in', models.DateField(verbose_name='Ngày Check-in')),
                ('check_out', models.DateField(verbose_name='Ngày Check-out')),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20, verbose_name='Trạng thái')),
                ('thanh_toan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Thanh toán (VNĐ)')),
            ],
        ),
        migrations.AlterField(
            model_name='phongluutru',
            name='loai_chuong',
            field=models.CharField(choices=[('Nhỏ', 'Nhỏ'), ('Trung Bình', 'Trung bình'), ('Lớn', 'Lớn')], max_length=20, verbose_name='Loại chuồng'),
        ),
        migrations.AlterField(
            model_name='phongluutru',
            name='trang_thai',
            field=models.CharField(choices=[('Trống', 'Trống'), ('Có Thú Cưng', 'Đã có thú cưng')], default='Trống', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
