# Generated by Django 5.1.5 on 2025-02-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_testmodel_delete_staffmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
