# Generated by Django 4.1.7 on 2025-02-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_appointment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
    ]
