# Generated by Django 4.1.7 on 2025-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
